### ISSUE TITLE
Create function for reload config

### ISSUE THREAD

**Issue by tyapochkin** [sancau/givemedata#5]
Sometimes config file might be changed while working with Jupyter Notebook. And if givemedata has been already imported we should have possibility to reload the new config file.

**Comment by sancau** [comment]
It's now possible to hot realod root Data provider by calling `init_provider()`

```
from givemedata import Data, init_provider

# conguration initially loaded automatically
# [GIVEMEDATA] Using config file at /etc/givemedata/givemedata.yaml

Data = init_provider()  # config reloaded
```
